SonarSource/echoes-react

README.md
package.json

I pushed my first commit straight to main to check that it was restricted... it was not.
It should be fixed now, but anyway, here's a PR!
I'll let you check my other commit on main :stuck_out_tongue:

DS-167 Improve README and skeleton of scripts

---

.cirrus.yml
.cirrus/Dockerfile
.cirrus/cirrus-sq-analysis.sh

I'll have to rebase once you've merged yours, but all seems good!

DS-190 Add SonarQube scan CI task

---

src/components/links/LinkBaseStyled.tsx
src/components/links/LinkStandalone.tsx

Focus style was wrong for the standalone link.
And the weight was wrong for all the links except the accent, they should all be semi-bold.

DS-186 Fix LinkStandalone focus style

---

stories/Icons-stories.tsx

No Jira, this was just for fun

[No Jira] Improve Icon Story

---

.cirrus.yml
.cirrus/Dockerfile
.cirrus/cirrus-sq-analysis.sh

use pre-release version of sonar-scanner-npm

NO-JIRA use pre-released sonar-scanner-npm package

---

src/components/radio-button-group/RadioButtonGroup.tsx
src/components/radio-button-group/__tests__/RadioButtonGroup-test.tsx
src/components/radio-button-group/index.ts
stories/RadioButtonGroup-stories.tsx

I changed the spacing a bit: this matches additional changes made by Marcio

DS-521 Support alignment prop on RadioButtonGroup

---

design-tokens/tokens/layer1/base.json
design-tokens/tokens/layer3/base.json
src/generated/design-tokens-base.css
src/generated/design-tokens-base.json
src/generated/design-tokens-dark.css
src/generated/design-tokens-light.css
src/generated/design-tokens-themed.json

Change small font size (12px) from regular to medium

Add typography max width

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

[ECHOES-488](https://sonarsource.atlassian.net/browse/ECHOES-488)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last line! …

ECHOES-488 Add Jira integration

---

package.json

[ECHOES-492](https://sonarsource.atlassian.net/browse/ECHOES-492)
[ECHOES-492]: https://sonarsource.atlassian.net/browse/ECHOES-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-492 Prepare version v0.11.0

---

.github/workflows/releasability.yml
.github/workflows/release.yml

[ECHOES-387](https://sonarsource.atlassian.net/browse/ECHOES-387)
[ECHOES-387]: https://sonarsource.atlassian.net/browse/ECHOES-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-387 Add Releasability check

---

.github/workflows/releasability.yml
.github/workflows/release.yml
package.json
src/components/dropdown-menu/DropdownMenuSubMenu.tsx

[ECHOES-495](https://sonarsource.atlassian.net/browse/ECHOES-495)
Part of 
[ECHOES-495]: https://sonarsource.atlassian.net/browse/ECHOES-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-495 Version 0.11.1

---

.cirrus.yml

[BUILD-7128](https://sonarsource.atlassian.net/browse/BUILD-7128)
Part of 
[BUILD-7128]: https://sonarsource.atlassian.net/browse/BUILD-7128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-7128 add github token env variable

---

package.json

[ECHOES-496](https://sonarsource.atlassian.net/browse/ECHOES-496)
[ECHOES-496]: https://sonarsource.atlassian.net/browse/ECHOES-496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-496 Prepare version 0.12.0

---

.github/workflows/release.yml

[ECHOES-498](https://sonarsource.atlassian.net/browse/ECHOES-498)
[ECHOES-498]: https://sonarsource.atlassian.net/browse/ECHOES-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-498 Skip releasability checks to allow RCs

---

design-tokens/tokens/layer1/base.json
src/generated/design-tokens-base.css
src/generated/design-tokens-base.json

[ECHOES-519](https://sonarsource.atlassian.net/browse/ECHOES-519)
Part of 
[ECHOES-519]: https://sonarsource.atlassian.net/browse/ECHOES-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-519 Fix small text tokens line height to work with icons

---

package.json

[ECHOES-526](https://sonarsource.atlassian.net/browse/ECHOES-526)
Part of 
[ECHOES-526]: https://sonarsource.atlassian.net/browse/ECHOES-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-526 Prepare version 0.12.0

---

package.json

[ECHOES-527](https://sonarsource.atlassian.net/browse/ECHOES-527)
[ECHOES-527]: https://sonarsource.atlassian.net/browse/ECHOES-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-527 Prepare version 0.13.0

---

package.json

[ECHOES-534](https://sonarsource.atlassian.net/browse/ECHOES-534)
Part of

ECHOES-534 Prepare for version 0.12.1

---

.github/workflows/release.yml

[ECHOES-535](https://sonarsource.atlassian.net/browse/ECHOES-535)
Part of 
[ECHOES-535]: https://sonarsource.atlassian.net/browse/ECHOES-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-535 Update release action to not release to npm with build number

---

.github/workflows/release.yml

[ECHOES-535](https://sonarsource.atlassian.net/browse/ECHOES-535)
Part of 
[ECHOES-535]: https://sonarsource.atlassian.net/browse/ECHOES-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-535 Fix release github action sha

---

src/components/messages/MessageStyles.tsx
src/components/radio-button-group/RadioButtonGroup.tsx
stories/message/MessageCallout-stories.tsx

This PR fixes the two small tickets we had in the sprint about Radio button and MessageCallout.

ECHOES-376 ECHOES-560 Components hardening

---

docs/RELEASING.md
package.json

[ECHOES-566](https://sonarsource.atlassian.net/browse/ECHOES-566)
[ECHOES-566]: https://sonarsource.atlassian.net/browse/ECHOES-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-566 Prepare for version 0.14

---

design-tokens/tokens/layer1/base.json
src/generated/design-tokens-base.css
src/generated/design-tokens-base.json

ECHOES-584
This change is following the change that we did for small text

ECHOES-584 Change helper-text typography design token to regular font-weight

---

src/components/modals/ModalTypes.ts

[ECHOES-585](https://sonarsource.atlassian.net/browse/ECHOES-585)
Based on https://github.com/SonarSource/echoes-react/commit/4b14eaa12d7173c3886f66bb5d06b866998f8f77#r152181382

ECHOES-585 Make modal title optional

---

src/components/form/FormRoot.tsx
src/components/modals/ModalAlert.tsx
src/components/modals/ModalForm.tsx
src/components/modals/__tests__/ModalForm-test.tsx
stories/ModalForm-stories.tsx

[ECHOES-591](https://sonarsource.atlassian.net/browse/ECHOES-591)
Part of [ECHOES-455](https://sonarsource.atlassian.net/browse/ECHOES-455)
[ECHOES-455]: https://sonarsource.atlassian.net/browse/ECHOES-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECHOES-591]: https://sonarsource.atlassian.net/browse/ECHOES-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-591 Add destructive ModalForm use case

---

i18n/keys.json
src/components/navbar/Navbar.tsx
src/components/navbar/__tests__/Navbar-test.tsx
src/components/navbar/index.ts
stories/Navbar-stories.tsx

[ECHOES-551](https://sonarsource.atlassian.net/browse/ECHOES-551)
ECHOES-551
Part of ECHOES-550
[ECHOES-551]: https://sonarsource.atlassian.net/browse/ECHOES-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-551 Navbar container

---

i18n/keys.json
src/components/buttons/ButtonIcon.tsx
src/components/navbar/NavbarAccount.tsx
src/components/navbar/NavbarAction.tsx
src/components/navbar/__tests__/NavbarAccount-test.tsx
src/components/navbar/__tests__/NavbarAction-test.tsx
src/components/navbar/index.ts
stories/Navbar-stories.tsx

[ECHOES-550](https://sonarsource.atlassian.net/browse/ECHOES-550)
[ECHOES-550]: https://sonarsource.atlassian.net/browse/ECHOES-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-550 Implement NavbarAction & NavbarAccount components

---

src/components/global-navigation/GlobalNavigationItem.tsx

[ECHOES-550](https://sonarsource.atlassian.net/browse/ECHOES-550)
Part of ECHOES-550
[ECHOES-550]: https://sonarsource.atlassian.net/browse/ECHOES-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-550 Fix path matching issue

---

src/components/global-navigation/GlobalNavigationHome.tsx
stories/GlobalNavigation-stories.tsx

[ECHOES-550](https://sonarsource.atlassian.net/browse/ECHOES-550)
[ECHOES-550]: https://sonarsource.atlassian.net/browse/ECHOES-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-550 Prevent text in Navigation Home from being underlined

---

package.json

[ECHOES-621](https://sonarsource.atlassian.net/browse/ECHOES-621)
Part of 
[ECHOES-621]: https://sonarsource.atlassian.net/browse/ECHOES-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-621 Prepare for version 0.16.0

---

src/components/global-navigation/GlobalNavigationAccount.tsx
src/components/global-navigation/GlobalNavigationAction.tsx
src/components/global-navigation/GlobalNavigationDropdownItem.tsx
src/components/global-navigation/GlobalNavigationItem.tsx
src/components/global-navigation/GlobalNavigationItemStyles.tsx
src/components/global-navigation/__tests__/GlobalNavigationDropdownItem-test.tsx
stories/GlobalNavigation-stories.tsx

[ECHOES-622](https://sonarsource.atlassian.net/browse/ECHOES-622)
[ECHOES-622]: https://sonarsource.atlassian.net/browse/ECHOES-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-622 Fixes for 0.15.1

---

.github/workflows/release.yml

[ECHOES-624](https://sonarsource.atlassian.net/browse/ECHOES-624)
[ECHOES-624]: https://sonarsource.atlassian.net/browse/ECHOES-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-624 Use previous version of the release workflow

---

src/components/global-navigation/GlobalNavigationAccount.tsx
src/components/global-navigation/GlobalNavigationAction.tsx
src/components/global-navigation/GlobalNavigationDropdownItem.tsx
src/components/global-navigation/GlobalNavigationItem.tsx
src/components/global-navigation/GlobalNavigationItemStyles.tsx
src/components/global-navigation/__tests__/GlobalNavigationDropdownItem-test.tsx
stories/GlobalNavigation-stories.tsx

ECHOES-622 GlobalNavigation fixes

---

design-tokens/tokens/layer3/base.json
src/components/breadcrumbs/BreadcrumbLink.tsx
src/components/breadcrumbs/Breadcrumbs.tsx
src/components/breadcrumbs/__tests__/BreadcrumbLink-test.tsx
src/components/breadcrumbs/__tests__/Breadcrumbs-test.tsx
src/components/breadcrumbs/index.ts
src/components/checkbox/__tests__/Checkbox-test.tsx
src/components/links/LinkStandalone.tsx
src/components/links/__tests__/Link-test.tsx
src/components/messages/__tests__/MessageCallout-test.tsx
src/components/messages/__tests__/MessageInline-test.tsx
src/components/spinner/__tests__/Spinner-test.tsx
src/generated/design-tokens-base.css
src/generated/design-tokens-base.json
stories/Breadcrumbs-stories.tsx

[ECHOES-593](https://sonarsource.atlassian.net/browse/ECHOES-593)
[ECHOES-594](https://sonarsource.atlassian.net/browse/ECHOES-594)
[ECHOES-593]: https://sonarsource.atlassian.net/browse/ECHOES-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECHOES-594]: https://sonarsource.atlassian.net/browse/ECHOES-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-593 & ECHOES-594 Add breadcrumb components

---

.github/workflows/PullRequestClosed.yml

[ECHOES-639](https://sonarsource.atlassian.net/browse/ECHOES-639)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[ECHOES-639]: https://sonarsource.atlassian.net/browse/ECHOES-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-639 Autoclose issues created by Jira integration

---

src/components/form/FormRoot.tsx
src/components/form/__tests__/Form-test.tsx

[ECHOES-640](https://sonarsource.atlassian.net/browse/ECHOES-640)
Part of 
[ECHOES-640]: https://sonarsource.atlassian.net/browse/ECHOES-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-640 Prevent default behaviour on form submit if no action submited

---

design-tokens/build.js

[ECHOES-646](https://sonarsource.atlassian.net/browse/ECHOES-646)
[ECHOES-646]: https://sonarsource.atlassian.net/browse/ECHOES-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-646 Take Tokens Studio "modify" fields into account in the "build-tokens" script

---

src/components/badges/RatingBadge.tsx
src/components/badges/RatingBadgeButton.tsx
src/components/badges/RatingBadgeLink.tsx
src/components/badges/__tests__/RatingBadge-test.tsx
src/components/badges/__tests__/RatingBadgeButton-test.tsx
src/components/badges/__tests__/RatingBadgeLink-test.tsx
src/components/badges/index.ts
stories/badges/RatingBadge-stories.tsx
stories/badges/RatingBadgeButton-stories.tsx
stories/badges/RatingBadgeLink-stories.tsx

[ECHOES-647](https://sonarsource.atlassian.net/browse/ECHOES-647)
[ECHOES-647]: https://sonarsource.atlassian.net/browse/ECHOES-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-647,648,649 Implement RatingBadge components

---

src/components/divider/Divider.tsx
stories/Divider-stories.tsx

[ECHOES-667](https://sonarsource.atlassian.net/browse/ECHOES-667)
Part of ECHOES-605
[ECHOES-667]: https://sonarsource.atlassian.net/browse/ECHOES-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-667 Remove margin from divider

---

src/components/card/CardRoot.tsx
stories/Card-stories.tsx

[ECHOES-671](https://sonarsource.atlassian.net/browse/ECHOES-671)
Part of 
[ECHOES-671]: https://sonarsource.atlassian.net/browse/ECHOES-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-671 Update Card component to properly forward props

---

src/components/checkbox/Checkbox.tsx
src/components/global-navigation/GlobalNavigationItemStyles.tsx
src/components/radio-button-group/RadioButtonGroup.tsx
src/components/select/SelectCommons.tsx
src/components/select/SelectItemCommons.tsx
src/components/text-input/TextInputBase.tsx

ECHOES-682
I double checked the values with Marcio

ECHOES-682 Fix outdated echoes-color-border tokens usage

---

package.json
src/components/checkbox/Checkbox.tsx
src/components/global-navigation/GlobalNavigationItemStyles.tsx
src/components/radio-button-group/RadioButtonGroup.tsx
src/components/select/SelectCommons.tsx
src/components/select/SelectItemCommons.tsx
src/components/text-input/TextInputBase.tsx

[ECHOES-683](https://sonarsource.atlassian.net/browse/ECHOES-683)
[ECHOES-683]: https://sonarsource.atlassian.net/browse/ECHOES-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-683 Prepare 0.17.2 release

---

.yarnrc.yml
package.json
src/components/badges/Badge.tsx
src/components/badges/__tests__/Badge-test.tsx
stories/badges/Badge-stories.tsx

[ECHOES-684](https://sonarsource.atlassian.net/browse/ECHOES-684)
[ECHOES-684]: https://sonarsource.atlassian.net/browse/ECHOES-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-684 New Badge component

---

.storybook/preview.tsx

[ECHOES-694](https://sonarsource.atlassian.net/browse/ECHOES-694)
[ECHOES-694]: https://sonarsource.atlassian.net/browse/ECHOES-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-694 Fix storybook docs pages to handle dark theme

---

design-tokens/tokens/$themes.json
design-tokens/tokens/layer3/dark.json
design-tokens/tokens/layer3/light.json
src/generated/design-tokens-dark.css
src/generated/design-tokens-light.css
src/generated/design-tokens-themed.json

[ECHOES-695](https://sonarsource.atlassian.net/browse/ECHOES-695)
Part of ECHOES-686
[ECHOES-695]: https://sonarsource.atlassian.net/browse/ECHOES-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-695 Change border token from severity badges critical to blocker

---

src/components/toggle-button-group/ToggleButtonGroup.tsx
src/components/toggle-button-group/__tests__/ToggleButtonGroup-test.tsx
stories/ToggleButtonGroup-stories.tsx

[ECHOES-722](https://sonarsource.atlassian.net/browse/ECHOES-722)
[ECHOES-722]: https://sonarsource.atlassian.net/browse/ECHOES-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-722 Allow ToggleButtonGroup to be disabled

---

package.json

[ECHOES-730](https://sonarsource.atlassian.net/browse/ECHOES-730)
[ECHOES-730]: https://sonarsource.atlassian.net/browse/ECHOES-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-730 Prepare for version 0.20

---

src/components/badges/Badge.tsx
src/components/badges/BadgeSeverity.tsx

[ECHOES-735](https://sonarsource.atlassian.net/browse/ECHOES-735)
I double checked badges usage in SQC and SQS and created a matching PR. But basically nothing will be negatively impacted by the change.
[ECHOES-735]: https://sonarsource.atlassian.net/browse/ECHOES-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-735 Change badges default display to be inline

---

design-tokens/tokens/layer2/light.json
src/generated/design-tokens-light.css
src/generated/design-tokens-themed.json

[PREQ-839](https://sonarsource.atlassian.net/browse/PREQ-839)
Part of 
[PREQ-839]: https://sonarsource.atlassian.net/browse/PREQ-839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PREQ-839 Fix badge highlight outline color

---

.github/renovate.json

ECHOES-737 Force renovate to trigger asap

---

.github/renovate.json

ECHOES-737 Properly ignore mantine update in renovate config and fix yarn update in netlify.toml

---

.github/renovate.json

ECHOES-737 Fix enabled managers and Style Dictionary exception

---

.github/renovate.json

ECHOES-737 Fix mantine and style-dictionary rules again

---

.github/renovate.json
netlify.toml
package.json

ECHOES-737 Fix renovate grouping and disable packages that need migration

---

renovate.json

ECHOES-737 Fix custom manager configureation

---

renovate.json

ECHOES-737 Extract yarn to separate PR

---

netlify.toml
renovate.json

ECHOES-737 Fix custom regex manager for netlify.toml

---

netlify.toml

ECHOES-737 Fix custom regex manager for netlify

---

renovate.json

ECHOES-737 Drop auto update of Yarn in netlify.toml

---

docs/RELEASING.md
package.json

[ECHOES-763](https://sonarsource.atlassian.net/browse/ECHOES-763)
[ECHOES-763]: https://sonarsource.atlassian.net/browse/ECHOES-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-763 Prepare for version 0.21

---

package.json

[ECHOES-783](https://sonarsource.atlassian.net/browse/ECHOES-783)
Part of

ECHOES-783 Prepare for version 0.22

---

package.json

[ECHOES-801](https://sonarsource.atlassian.net/browse/ECHOES-801)
Part of 
[ECHOES-801]: https://sonarsource.atlassian.net/browse/ECHOES-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Prepare for version 0.23

---

src/components/checkbox/Checkbox.tsx
src/components/form/FormField.tsx
src/components/radio-button-group/RadioButton.tsx
src/components/selection-cards/SelectionCards.tsx

[ECHOES-809](https://sonarsource.atlassian.net/browse/ECHOES-809)
[ECHOES-809]: https://sonarsource.atlassian.net/browse/ECHOES-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-809 Only add 'data-disabled' when disabled

---

src/components/messages/MessageCallout.tsx
src/components/messages/__tests__/MessageCallout-test.tsx
stories/Form-stories.tsx
stories/ModalForm-stories.tsx
stories/message/MessageCallout-stories.tsx

[ECHOES-782](https://sonarsource.atlassian.net/browse/ECHOES-782)
[ECHOES-782]: https://sonarsource.atlassian.net/browse/ECHOES-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-782 Use "children" instead of a "text" prop in MessageCallout

---

src/components/form/FormField.tsx
src/components/messages/MessageCallout.tsx
src/components/messages/MessageInline.tsx
src/components/messages/MessageScreenReaderPrefix.tsx
src/components/messages/MessageStyles.tsx
src/components/messages/MessageTypes.tsx
src/components/messages/__tests__/MessageCallout-test.tsx
src/components/messages/__tests__/MessageInline-test.tsx
src/components/messages/index.ts
stories/Form-stories.tsx
stories/ModalForm-stories.tsx
stories/message/MessageCallout-stories.tsx
stories/message/MessageInline-stories.tsx

[ECHOES-796](https://sonarsource.atlassian.net/browse/ECHOES-796)
[ECHOES-796]: https://sonarsource.atlassian.net/browse/ECHOES-796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-796 Rename "type" prop to "variety" for MessageCallout, MessageInline

---

package.json

[ECHOES-819](https://sonarsource.atlassian.net/browse/ECHOES-819)
[ECHOES-819]: https://sonarsource.atlassian.net/browse/ECHOES-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-819 Bump version to 1.0.0 in v1 common branch

---

i18n/keys.json
src/components/index.ts
src/components/pagination/Pagination.tsx
src/components/pagination/PaginationTypes.ts
src/components/pagination/__tests__/Pagination-test.tsx
src/components/pagination/__tests__/utils-test.ts
src/components/pagination/index.ts
src/components/pagination/utils.ts
stories/Pagination-stories.tsx

[ECHOES-803](https://sonarsource.atlassian.net/browse/ECHOES-803)
Part of 
[ECHOES-803]: https://sonarsource.atlassian.net/browse/ECHOES-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-803 Implement the Pagination component

---

package.json
src/components/badges/BadgeSeverity.tsx
src/components/badges/index.ts

[ECHOES-820](https://sonarsource.atlassian.net/browse/ECHOES-820)
Checks are passing with this build https://github.com/SonarSource/sonarcloud-webapp/pull/2587/checks
Draft release here for when this is reviewed: https://github.com/SonarSource/echoes-react/releases
[ECHOES-820]: https://sonarsource.atlassian.net/browse/ECHOES-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-820 Fix BadgeSeverity props & exports

---

design-tokens/build.js
src/generated/tailwindConfig.js

[ECHOES-178](https://sonarsource.atlassian.net/browse/ECHOES-178)
Based on https://github.com/tailwindlabs/tailwindcss/blob/v3/stubs/config.full.js
[ECHOES-178]: https://sonarsource.atlassian.net/browse/ECHOES-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-178 Fix dimension preset

---

src/components/text-input/TextInput.tsx

[ECHOES-836](https://sonarsource.atlassian.net/browse/ECHOES-836)
Part of 
[ECHOES-836]: https://sonarsource.atlassian.net/browse/ECHOES-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-836 Improve textInput typing to also accept dir

---

.storybook/preview.tsx
design-tokens/tokens/layer3/dark.json
src/common/helpers/test-utils.tsx
src/components/banner/BannerStyles.tsx
src/components/banner/__tests__/Banner-test.tsx
src/components/banner/__tests__/__snapshots__/Banner-test.tsx.snap
src/components/global-navigation/__tests__/GlobalNavigation-test.tsx
src/components/global-navigation/__tests__/GlobalNavigationDropdownItem-test.tsx
src/components/global-navigation/__tests__/GlobalNavigationItem-test.tsx
src/components/modals/Modal.tsx
src/components/modals/ModalAlert.tsx
src/components/modals/ModalForm.tsx
src/components/modals/ModalTypes.ts
src/components/modals/__tests__/Modal-test.tsx
src/components/modals/__tests__/ModalAlert-test.tsx
src/components/modals/__tests__/ModalForm-test.tsx
src/generated/design-tokens-dark.css
stories/ModalAlert-stories.tsx

[ECHOES-832](https://sonarsource.atlassian.net/browse/ECHOES-832)
[ECHOES-835](https://sonarsource.atlassian.net/browse/ECHOES-835)
[ECHOES-643](https://sonarsource.atlassian.net/browse/ECHOES-643)
Part of 
[ECHOES-832]: https://sonarsource.atlassian.net/browse/ECHOES-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECHOES-835]: https://sonarsource.atlassian.net/browse/ECHOES-835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECHOES-643]: https://sonarsource.atlassian.net/browse/ECHOES-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-832 ECHOES-835 ECHOES-643 V1 hardening

---

src/components/banner/Banner.tsx
src/components/banner/BannerScreenReaderPrefix.tsx
src/components/banner/BannerStyles.tsx
src/components/banner/BannerTypes.tsx
src/components/banner/__tests__/Banner-test.tsx
src/components/banner/index.ts
stories/Banner-stories.tsx

[ECHOES-818](https://sonarsource.atlassian.net/browse/ECHOES-818)
Matching PR https://github.com/SonarSource/sonarcloud-webapp/pull/2742
[ECHOES-818]: https://sonarsource.atlassian.net/browse/ECHOES-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-818 Rename Banner type prop to variety

---

.storybook/preview.tsx

[ECHOES-833](https://sonarsource.atlassian.net/browse/ECHOES-833)
[ECHOES-833]: https://sonarsource.atlassian.net/browse/ECHOES-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-833 Remove SSR warning in storybook

---

src/components/spinner/Spinner.tsx
src/components/spinner/SpinnerStyles.tsx
stories/Spinner-stories.tsx

[ECHOES-799](https://sonarsource.atlassian.net/browse/ECHOES-799)
[ECHOES-799]: https://sonarsource.atlassian.net/browse/ECHOES-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-799 Fix spinner double node bug

---

README.md

[ECHOES-696](https://sonarsource.atlassian.net/browse/ECHOES-696)
Part of 
[ECHOES-696]: https://sonarsource.atlassian.net/browse/ECHOES-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-696 Update library readme

---

src/components/badges/Badge.tsx
src/components/badges/BadgeCounter.tsx
src/components/badges/BadgeSeverity.tsx
src/components/badges/RatingBadge.tsx
src/components/badges/RatingBadgeButton.tsx
src/components/badges/RatingBadgeLink.tsx
src/components/banner/Banner.tsx
src/components/buttons/Button.tsx
src/components/buttons/ButtonAsLink.tsx
src/components/buttons/ButtonGroup.tsx
src/components/buttons/ButtonIcon.tsx
src/components/buttons/ButtonTypes.ts
src/components/checkbox-group/CheckboxGroup.tsx
src/components/checkbox/Checkbox.tsx
src/types/utils.ts

[ECHOES-171](https://sonarsource.atlassian.net/browse/ECHOES-171)
Part of 
[ECHOES-171]: https://sonarsource.atlassian.net/browse/ECHOES-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-171 Add Badge, Banner, Buttons and CheckBox components TSDoc

---

src/common/components/DismissButton.tsx
src/components/badges/Badge.tsx
src/components/badges/BadgeSeverity.tsx
src/components/buttons/Button.tsx
src/components/buttons/ButtonIcon.tsx
src/components/buttons/ButtonStyles.tsx
src/components/dropdown-menu/DropdownMenu.tsx
src/components/dropdown-menu/DropdownMenuItemBase.tsx
src/components/dropdown-menu/__tests__/DropdownMenu-test.tsx
src/components/links/LinkBase.tsx
src/components/radio-button-group/RadioButtonGroup.tsx
src/components/search-input/SearchInput.tsx
src/components/search-input/SearchInputClearButton.tsx
src/components/selection-cards/SelectionCards.tsx
src/components/text-area/TextArea.tsx
src/components/text-input/TextInput.tsx
stories/dropdown-menu/DropdownMenu-stories.tsx
stories/helpers/MenuButton.tsx

[ECHOES-874](https://sonarsource.atlassian.net/browse/ECHOES-874)

ECHOES-874 Add reloadDocument to download links (or links-as-buttons)

---

src/common/components/NavLinkBase.tsx
src/components/buttons/Button.tsx
src/components/dropdown-menu/DropdownMenuItemLinkDownload.tsx
src/components/links/LinkBase.tsx
stories/Button-stories.tsx
stories/link/LinkStandalone-stories.tsx

[ECHOES-825](https://sonarsource.atlassian.net/browse/ECHOES-825)
[ECHOES-825]: https://sonarsource.atlassian.net/browse/ECHOES-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-825 Use consistent download link props

---

package.json

[ECHOES-896](https://sonarsource.atlassian.net/browse/ECHOES-896)
[ECHOES-896]: https://sonarsource.atlassian.net/browse/ECHOES-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-896 Prepare for version 1.2.0

---

src/components/sidebar-navigation/SidebarNavigationGroup.tsx
src/components/sidebar-navigation/__tests__/SidebarNavigationGroup-test.tsx
src/components/sidebar-navigation/__tests__/__snapshots__/SidebarNavigationItem-test.tsx.snap
stories/Sidebar-stories.tsx

[ECHOES-904](https://sonarsource.atlassian.net/browse/ECHOES-904)
[ECHOES-904]: https://sonarsource.atlassian.net/browse/ECHOES-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-904 Sidebar navigation Group

---

src/components/sidebar-navigation/SidebarNavigationHeader.tsx
src/components/sidebar-navigation/__tests__/SidebarNavigationHeader-test.tsx
stories/sidebar-navigation/SidebarNavigationHeader-stories.tsx

[ECHOES-903](https://sonarsource.atlassian.net/browse/ECHOES-903)
Based on yours to have the overflow helper
[ECHOES-903]: https://sonarsource.atlassian.net/browse/ECHOES-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-903 Implement Sidebar Navigation Header

---

design-tokens/tokens/layer3/dark.json
design-tokens/tokens/layer3/light.json
src/common/helpers/__tests__/__snapshots__/useBottomShadowScroll-test.tsx.snap
src/common/helpers/__tests__/useBottomShadowScroll-test.tsx
src/common/helpers/__tests__/useResizeObserver-test.tsx
src/common/helpers/useBottomShadowScroll.tsx
src/common/helpers/useResizeObserver.ts
src/components/modals/ModalBody.tsx
src/components/sidebar-navigation/SidebarNavigationBody.tsx
src/components/sidebar-navigation/SidebarNavigationItemStyles.tsx
src/components/sidebar-navigation/__tests__/SidebarNavigationBody-test.tsx
src/components/sidebar-navigation/index.ts
src/generated/design-tokens-dark.css
src/generated/design-tokens-light.css
src/generated/design-tokens-themed.json

[ECHOES-916](https://sonarsource.atlassian.net/browse/ECHOES-916)
Part of 
[ECHOES-916]: https://sonarsource.atlassian.net/browse/ECHOES-916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-916 Add sidebar-navigation scroll shadow

---

src/components/sidebar-navigation/SidebarNavigation.tsx
src/components/sidebar-navigation/SidebarNavigationHeader.tsx

[ECHOES-906](https://sonarsource.atlassian.net/browse/ECHOES-906)
Part of 
[ECHOES-906]: https://sonarsource.atlassian.net/browse/ECHOES-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-906 Fix sidebar navigation header top spacing

---

design-tokens/tokens/layer3/light.json
src/generated/design-tokens-light.css
src/generated/design-tokens-themed.json

[ECHOES-794](https://sonarsource.atlassian.net/browse/ECHOES-794)
Part of 
[ECHOES-794]: https://sonarsource.atlassian.net/browse/ECHOES-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-794 Fix input controllers border colors

---

design-tokens/tokens/layer3/base.json
src/components/layout/LayoutTypes.ts
src/components/layout/page-header/PageHeader.tsx
src/components/layout/page-header/__tests__/PageHeader-test.tsx
src/generated/design-tokens-base.css
src/generated/design-tokens-base.json
stories/layout/Layout-stories.tsx

[ECHOES-922](https://sonarsource.atlassian.net/browse/ECHOES-922)
[ECHOES-923](https://sonarsource.atlassian.net/browse/ECHOES-923)
[ECHOES-922]: https://sonarsource.atlassian.net/browse/ECHOES-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECHOES-923]: https://sonarsource.atlassian.net/browse/ECHOES-923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-922 ECHOES-923 Implement PageHeader sticky behavior

---

src/components/layout/LayoutSlots.tsx
src/components/layout/sidebar-navigation/SidebarNavigationItem.tsx
stories/layout/Layout-stories.tsx

[ECHOES-929](https://sonarsource.atlassian.net/browse/ECHOES-929)
[ECHOES-929]: https://sonarsource.atlassian.net/browse/ECHOES-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-929 Small hardening for the new Layout

---

src/components/index.ts
src/components/layout/global-navigation/index.ts

[ECHOES-931](https://sonarsource.atlassian.net/browse/ECHOES-931)
[ECHOES-931]: https://sonarsource.atlassian.net/browse/ECHOES-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-931 Preserve deprecated GlobalNavigation export

---

design-tokens/tokens/layer3/dark.json
design-tokens/tokens/layer3/light.json
src/components/layout/sidebar-navigation/SidebarNavigation.tsx
src/components/layout/sidebar-navigation/SidebarNavigationAccordionItem.tsx
src/components/layout/sidebar-navigation/SidebarNavigationHeader.tsx
src/components/layout/sidebar-navigation/SidebarNavigationItem.tsx
src/components/layout/sidebar-navigation/SidebarNavigationItemStyles.tsx
src/generated/design-tokens-dark.css
src/generated/design-tokens-light.css
src/generated/design-tokens-themed.json

[ECHOES-930](https://sonarsource.atlassian.net/browse/ECHOES-930)
[ECHOES-930]: https://sonarsource.atlassian.net/browse/ECHOES-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-930 Fix sidebar navigation colors by introducing custom layer 3 tokens

---

src/components/layout/sidebar-navigation/SidebarNavigationAccordionItem.tsx
src/components/layout/sidebar-navigation/SidebarNavigationItem.tsx
src/components/layout/sidebar-navigation/__tests__/SidebarNavigationAccordionItem-test.tsx
stories/layout/sidebar-navigation/SidebarNavigation-stories.tsx
stories/layout/sidebar-navigation/SidebarNavigationAccordionItem-stories.tsx
stories/layout/sidebar-navigation/SidebarNavigationItem-stories.tsx

[ECHOES-934](https://sonarsource.atlassian.net/browse/ECHOES-934)
[ECHOES-934]: https://sonarsource.atlassian.net/browse/ECHOES-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-934 Add optional suffix to SidebarNavigation Item and AccordionItem

---

src/common/components/Toast.tsx
src/components/layout/LayoutSlots.tsx

[ECHOES-946](https://sonarsource.atlassian.net/browse/ECHOES-946)
Part of 
There was an issue with the fluid page content that didn't take the full width if the contend was small, this fixes it.
[ECHOES-946]: https://sonarsource.atlassian.net/browse/ECHOES-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-946 Fix broken fluid layout and fix broken Toast imports

---

.github/workflows/unified-dogfooding.yml

[ECHOES-952](https://sonarsource.atlassian.net/browse/ECHOES-952)
Part of 
[ECHOES-952]: https://sonarsource.atlassian.net/browse/ECHOES-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-952 Fix unified-dogfooding artifactory reader role

---

src/components/layout/global-navigation/GlobalNavigationItem.tsx
src/components/layout/global-navigation/__tests__/GlobalNavigationItem-test.tsx

[ECHOES-950](https://sonarsource.atlassian.net/browse/ECHOES-950)
From branch 1.2
[ECHOES-950]: https://sonarsource.atlassian.net/browse/ECHOES-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ECHOES-950 Allow override nav item active state (#499)
