.github/CODEOWNERS
it appears only one team can be owner of a repository (RE checks are reporting this repo as not respecting this rule)
=> BUILD-4135 Update CODEOWNERS

src/common/components/NavLinkBase.tsx, src/components/dropdown-menu/DropdownMenuItemLink.tsx, src/components/dropdown-menu/DropdownMenuItemLinkDownload.tsx, src/components/links/Link.tsx, src/components/links/LinkBase.tsx, src/components/links/LinkStandalone.tsx, src/components/links/__tests__/Link-test.tsx, src/components/links/__tests__/LinkStandalone-test.tsx
I suggest we change linkbase to a simpler implementation where we extract the navlink part that is just for the DropdownMenuItemLink. It also allows to fully rely on the `shouldOpenInNewTab` props to display the external icon or not.
=> DS-510 Simplify the LinkBase implementation

design-tokens/build.js, src/generated/design-tokens-dark.css, src/generated/design-tokens-light.css, stories/ThemeProvider-stories.tsx
**Theme Inception**
This PR adds support for nesting theme providers so that it is possible to render a subtree of components using the light theme within the context of a dark theme. For example,
```jsx
<ThemeProvider theme={Theme.Dark}>
<Text>I should be dark theme</Text>
<ThemeProvider theme={Theme.light}>
<Text>I should be light theme</Text>
</ThemeProvider>
</ThemeProvider>
```
This is achieved by making the following change to the generated CSS for the light theme,
```diff
- :root {
+ :root, [data-echoes-theme='light'] {
```
For a motivating example see https://github.com/SonarSource/sonarcloud-webapp/pull/1236.
=> ECHOES-490 Support nested theme providers

docs/RELEASING.md, package.json, src/components/dropdown-menu/DropdownMenuSubMenu.tsx
[ECHOES-493](https://sonarsource.atlassian.net/browse/ECHOES-493)
[ECHOES-493]: https://sonarsource.atlassian.net/browse/ECHOES-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-493 Add check on .d.ts generation

i18n/keys.json, src/components/messages/MessageCallout.tsx, src/components/messages/MessageDismissButton.tsx, src/components/messages/MessageInline.tsx, src/components/messages/MessageScreenReaderPrefix.tsx, src/components/messages/MessageStyles.tsx, src/components/messages/MessageTypes.tsx, src/components/messages/__tests__/MessageCallout-test.tsx, src/components/messages/__tests__/MessageInline-test.tsx, src/components/messages/index.ts, stories/Icons-stories.tsx, stories/message/MessageCallout-stories.tsx, stories/message/MessageInline-stories.tsx
[ECHOES-292](https://sonarsource.atlassian.net/browse/ECHOES-292)
[ECHOES-292]: https://sonarsource.atlassian.net/browse/ECHOES-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-292 Add new Inline Message and Callout components

src/components/dropdown-menu/DropdownMenu.tsx
[ECHOES-533](https://sonarsource.atlassian.net/browse/ECHOES-533)
Part of 
[ECHOES-533]: https://sonarsource.atlassian.net/browse/ECHOES-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-533 Fix broken ids and a11y in DropdownMenu component

src/components/form/FormFieldLabel.tsx, src/components/form/index.ts, stories/Form-stories.tsx
[ECHOES-531](https://sonarsource.atlassian.net/browse/ECHOES-531)
Build doesn't pass because of the broken code from the target branch
[ECHOES-531]: https://sonarsource.atlassian.net/browse/ECHOES-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-531 Implement FormFieldLabel

src/components/checkbox/Checkbox.tsx, src/components/checkbox/__tests__/Checkbox-test.tsx, stories/Checkbox-stories.tsx
[ECHOES-542](https://sonarsource.atlassian.net/browse/ECHOES-542)
The [Figma page](https://www.figma.com/design/wYk5yGLz6MYC2hdu70IGql/(0.13.0)-Form-Fields?node-id=80-200) for checkboxes has not been updated to remove the disabled state from the label and description.
- The checkbox will now always have an id. As consequence, the second argument to the `onCheck` callback will never be `undefined`.
- The `aria-disabled` property on the checkbox container was renamed to `data-disabled`.
- The container no longer renders as a label element. Now, the label renders as a label element. See [Wrapping Everything Inside \<label>](https://www.smashingmagazine.com/2023/02/guide-accessible-form-validation/#wrapping-everything-inside-label) for a justification.
- The disabled styles were removed from …
=> ECHOES-542 Align Checkbox

src/components/select/SelectCommons.tsx
[ECHOES-568](https://sonarsource.atlassian.net/browse/ECHOES-568)
There are a bunch of tests failing in the product because Mantine is adding the same label to the input element and option dropdown wrapper element.
[ECHOES-568]: https://sonarsource.atlassian.net/browse/ECHOES-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-568 Migration Fixes

src/components/checkbox/index.ts, src/components/text-area/TextArea.tsx, src/components/text-area/index.ts, src/components/text-input/TextInput.tsx, src/components/text-input/index.ts
[ECHOES-569](https://sonarsource.atlassian.net/browse/ECHOES-569)
Some components were not exporting their prop types.
[ECHOES-569]: https://sonarsource.atlassian.net/browse/ECHOES-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-569 Expose Component Prop Types

src/components/form/FormHeader.tsx, src/components/form/FormSection.tsx
[ECHOES-581](https://sonarsource.atlassian.net/browse/ECHOES-581)
Part of ECHOES-455
It fixes this issue: 
[ECHOES-581]: https://sonarsource.atlassian.net/browse/ECHOES-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-581 Remove the extra bottom margin to form/section headers when there is no description

src/components/checkbox-group/CheckboxGroup.tsx, src/components/form/FormField.tsx, src/components/form/FormFieldLabel.tsx, src/components/form/__tests__/FormField-test.tsx, src/components/form/useFormFieldA11y.ts, src/components/popover/Popover.tsx, src/components/popover/index.ts, src/components/radio-button-group/RadioButtonGroup.tsx, src/components/select/SelectCommons.tsx, src/components/text-area/TextArea.tsx, src/components/text-input/TextInput.tsx, src/components/text-input/TextInputBase.tsx, src/components/toggle-tip/ToggleTip.tsx, src/components/toggle-tip/index.ts, stories/FormField-stories.tsx, stories/TextInput-stories.tsx, stories/helpers/arg-types.tsx
[ECHOES-583](https://sonarsource.atlassian.net/browse/ECHOES-583)
Part of [ECHOES-455](https://sonarsource.atlassian.net/browse/ECHOES-455)
Fixes:
[ECHOES-455]: https://sonarsource.atlassian.net/browse/ECHOES-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ECHOES-583]: https://sonarsource.atlassian.net/browse/ECHOES-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-583 Add helpToggletip prop to form fields

src/components/modals/ModalForm.tsx
[ECHOES-587](https://sonarsource.atlassian.net/browse/ECHOES-587)
I migrated the confirmation dialogs in the organization settings to use the ModalForm component but they use the `Danger` variety for the submit button. I thought it made sense to allow the variety of the submit button to be overridden instead of ejecting out of ModalForm.
Current Dialog
With ModalForm
[ECHOES-587]: https://sonarsource.atlassian.net/browse/ECHOES-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-587 Allow overriding the submit button variety of ModalForm

src/components/global-navigation/GlobalNavigationDropdownItem.tsx, src/components/global-navigation/GlobalNavigationHome.tsx, src/components/global-navigation/GlobalNavigationItem.tsx, src/components/global-navigation/GlobalNavigationItemsContainer.tsx, stories/GlobalNavigation-stories.tsx
- Removes the children wrapping logic in the Item Container and wraps the Item and DownloadItem directly
- This allows fragments around Items in the products
- Code is simpler and not as brittle. Also no more "magic"
- Add `reloadDocument` prop to Home
Based on the WIP [integration in SQC](https://github.com/SonarSource/sonarcloud-webapp/tree/jay/navbar-migration-sqc)
=> ECHOES-550 Fix issues with GlobalNavigation

src/components/modals/ModalForm.tsx, src/components/modals/__tests__/ModalForm-test.tsx
[ECHOES-633](https://sonarsource.atlassian.net/browse/ECHOES-633)
Part of 
[ECHOES-633]: https://sonarsource.atlassian.net/browse/ECHOES-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-633 ModalForm shouldn't throw on promise onSubmit reject

src/components/badges/Badge.tsx, src/components/badges/__tests__/Badge-test.tsx, stories/badges/Badge-stories.tsx
[ECHOES-684](https://sonarsource.atlassian.net/browse/ECHOES-684)
I missed this in the design, found it in the docs :sweat_smile: 
[ECHOES-684]: https://sonarsource.atlassian.net/browse/ECHOES-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-684 Add optional icon prop to Badge

src/components/search-input/SearchInput.tsx
[ECHOES-806](https://sonarsource.atlassian.net/browse/ECHOES-806)
Not super obvious but when switching for the too long message that displayed in the placeholder and the one that's on the right we can see a small move up of the text, adding this top margin aligns it perfectly.
No need to do a patch release for that.
=> ECHOES-806 Fix small alignment issue with min length message in SearchInput

src/components/dropdown-menu/DropdownMenuItemBase.tsx, stories/dropdown-menu/DropdownMenu-stories.tsx
[ECHOES-819](https://sonarsource.atlassian.net/browse/ECHOES-819)
Easily validate by adding a badge as a suffix and adding lots of text in the label.
The ellipsis should kick in, and the badge should still be rendered appropriately
[ECHOES-819]: https://sonarsource.atlassian.net/browse/ECHOES-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-790 Fix DropdownMenu items' overflow handling

src/common/helpers/test-utils.tsx, src/components/checkbox-group/CheckboxGroup.tsx, src/components/checkbox/Checkbox.tsx, src/components/checkbox/__tests__/Checkbox-test.tsx, src/components/dropdown-menu/DropdownMenu.tsx, src/components/radio-button-group/RadioButtonTypes.ts, src/components/select/SelectCommons.tsx, src/components/text-input/TextInputBase.tsx, src/types/utils.ts, stories/select/Select-stories.tsx
[ECHOES-645](https://sonarsource.atlassian.net/browse/ECHOES-645)
Allowing helpText with no label on the following components:
- CheckboxGroup
- RadioButtonGroup
- Select
- SelectAsync
- TextArea
- TextInput
Only the Checkbox & DropdownMenuItems keep the restriction of needing a label for the helpText, because of their structure
[ECHOES-645]: https://sonarsource.atlassian.net/browse/ECHOES-645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-645 Allow helpText with no label

.github/workflows/releasability.yml, .github/workflows/release.yml
[ECHOES-966](https://sonarsource.atlassian.net/browse/ECHOES-966)
Part of 
[ECHOES-966]: https://sonarsource.atlassian.net/browse/ECHOES-966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ECHOES-966 Make it possible to manually run the releasability check, re-enable releasbility check on release job
